# Generated by Django 2.1.3 on 2018-11-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='brc_base_url',
            field=models.URLField(blank=True, default='http://localhost:8003', help_text='Besluit API van het Besluit registratie component', verbose_name='BRC basis URL'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='ztc_mor_informatieobjecttype_image_uuid',
            field=models.CharField(blank=True, max_length=36, verbose_name='Informatieobjecttype "Afbeelding" UUID'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='drc_base_url',
            field=models.URLField(blank=True, default='http://localhost:8001', help_text='Documenten API van het Document registratie component', verbose_name='DRC basis URL'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='orc_base_url',
            field=models.URLField(blank=True, default='http://localhost:8888', help_text='Zaken API van het Zaak registratie component', verbose_name='ORC basis URL'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='zrc_base_url',
            field=models.URLField(blank=True, default='http://localhost:8000', help_text='Zaken API van het Zaak registratie component', verbose_name='ZRC basis URL'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='ztc_base_url',
            field=models.URLField(blank=True, default='http://localhost:8002', help_text='Catalogus API van het Zaaktypecatalogus component', verbose_name='ZTC basis URL'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='ztc_catalogus_uuid',
            field=models.CharField(blank=True, help_text='Het UUID van de catalogus in het ZTC', max_length=36, verbose_name='Standaard catalogus UUID'),
        ),
    ]
