# Generated by Django 2.1.3 on 2018-11-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20181120_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='brc_client_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='brc_secret',
            field=models.CharField(blank=True, max_length=512, verbose_name='Secret'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='drc_client_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='drc_secret',
            field=models.CharField(blank=True, max_length=512, verbose_name='Secret'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='global_api_client_id',
            field=models.CharField(blank=True, help_text='Deze Client ID wordt voor alle APIs gebruikt, tenzij eenAPI specifieke Client ID is opgegeven', max_length=255, verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='global_api_secret',
            field=models.CharField(blank=True, help_text='Dit Secret wordt voor alle APIs gebruikt, tenzij eenAPI specifiek Secret is opgegeven', max_length=512, verbose_name='Secret'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='orc_client_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='orc_secret',
            field=models.CharField(blank=True, max_length=512, verbose_name='Secret'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='zrc_client_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='zrc_secret',
            field=models.CharField(blank=True, max_length=512, verbose_name='Secret'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='ztc_client_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='ztc_secret',
            field=models.CharField(blank=True, max_length=512, verbose_name='Secret'),
        ),
    ]
