# Generated by Django 2.0.3 on 2018-12-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20181127_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='brc_base_url',
            field=models.CharField(blank=True, default='http://localhost:8003/api/v1/', help_text='Besluit API van het Besluit registratie component', max_length=255, verbose_name='BRC basis URL'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='drc_base_url',
            field=models.CharField(blank=True, default='http://localhost:8001/api/v1/', help_text='Documenten API van het Document registratie component', max_length=255, verbose_name='DRC basis URL'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='global_api_client_id',
            field=models.CharField(blank=True, help_text='Deze Client ID wordt voor alle APIs gebruikt, tenzij een API specifieke Client ID is opgegeven', max_length=255, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='global_api_secret',
            field=models.CharField(blank=True, help_text='Dit Secret wordt voor alle APIs gebruikt, tenzij een API specifiek Secret is opgegeven', max_length=512, verbose_name='Secret'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='orc_base_url',
            field=models.CharField(blank=True, default='http://localhost:8010/api/v1/', help_text='Zaken API van het Zaak registratie component', max_length=255, verbose_name='ORC basis URL'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='zrc_base_url',
            field=models.CharField(blank=True, default='http://localhost:8000/api/v1/', help_text='Zaken API van het Zaak registratie component', max_length=255, verbose_name='ZRC basis URL'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='ztc_base_url',
            field=models.CharField(blank=True, default='http://localhost:8002/api/v1/', help_text='Catalogus API van het Zaaktypecatalogus component', max_length=255, verbose_name='ZTC basis URL'),
        ),
    ]
