# Generated by Django 2.1.3 on 2019-01-22 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20181204_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherZTC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(blank=True, help_text='Catalogus API van het Zaaktypecatalogus component', max_length=255, verbose_name='ZTC basis URL')),
                ('client_id', models.CharField(blank=True, max_length=255, verbose_name='Client ID')),
                ('secret', models.CharField(blank=True, max_length=512, verbose_name='Secret')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.SiteConfiguration')),
            ],
        ),
    ]
