# Generated by Django 2.1.3 on 2019-01-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20181204_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='google_api_key',
            new_name='google_maps_api_key',
        ),
    ]
