# Generated by Django 2.1.3 on 2019-01-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20190108_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='google_maps_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default='52.36991896035238', max_digits=9, verbose_name='Google maps latitude'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='google_maps_long',
            field=models.DecimalField(blank=True, decimal_places=6, default='4.897787135976614', help_text='Deze coördinaten worden standaard op de kaart weergegeven', max_digits=9, verbose_name='Google maps longitude'),
        ),
    ]
