# Generated by Django 2.1.3 on 2019-01-22 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20190108_1021'),
        ('demo', '0005_otherztc'),
    ]

    operations = [
    ]
