# Generated by Django 2.1.3 on 2019-07-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_auto_20190318_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='brp_api_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='API-sleutel'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='brp_base_url',
            field=models.CharField(blank=True, help_text='Basis registratie (ingeschreven) personen API.', max_length=255, verbose_name='BRP basis URL'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='callback_url',
            field=models.URLField(blank=True, help_text='De URL van deze demo applicatie waar het NRC berichten naar toe kan sturen.', verbose_name='Callback URL'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nc_base_url',
            field=models.CharField(blank=True, default='http://localhost:8004/api/v1/', help_text='Notificatie API van het Notificatie routering component', max_length=255, verbose_name='NRC basis URL'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='orc_base_url',
            field=models.CharField(blank=True, default='http://localhost:8010/api/v1/', help_text='Overige registraties API (niet meer in gebruik).', max_length=255, verbose_name='ORC basis URL'),
        ),
    ]
