# Generated by Django 2.1.3 on 2020-09-28 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zgw_consumers', '0011_remove_service_extra'),
        ('demo', '0011_auto_20190807_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='objects_api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects_config', to='zgw_consumers.Service'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='objecttypes_api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objecttypes_config', to='zgw_consumers.Service'),
        ),
    ]
