# Generated by Django 2.1.3 on 2020-10-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_auto_20200928_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='objecttypes_mor_objecttype_uuid',
            field=models.CharField(blank=True, max_length=36, verbose_name='Objecttype "Melding" UUID'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='objecttypes_mor_objecttype_version',
            field=models.SmallIntegerField(null=True, blank=True, verbose_name='Objecttype "Melding" Version'),
        ),
    ]
